### ISSUE TITLE
Cant get jar file to work

### ISSUE THREAD

**Issue by johncleveland** [mkeet/CLaRO#1]
I am unable to get the jar file to execute. Using ubuntu 18.04 LTS. Trying java 8, 11

**Comment by mkeet** [comment]
that shouldn't matter. I have it working with java 8; see screenshot after a fresh download of the jar file just now (to double-check again that we did not make a mistake):
![Screenshot 2020-08-30 at 12 04 22](https://user-images.githubusercontent.com/6412100/91656387-a5841400-eab8-11ea-9207-d6d80bf73621.png)
Zola coded it on Ubuntu, so at least one configuration on that OS works. He'll reply with those details.

**Comment by johncleveland** [comment]
This is the command that I am using from the CQEditor directory (Java 11): 

java --module-path /home/yxs8495/Software/openjfx-11.0.2_linux-x64_bin-sdk/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml,javafx.base,javafx.media,javafx.web,javafx.swing -jar Tool.jar 

There is some configuration that I am missing. Any help you could provide would be most appreciative. 

-thanx

**Comment by AdeebNqo** [comment]
Hi @johncleveland ,

Are you getting an error message? If so, can you please post it.

**Comment by johncleveland** [comment]
[failure.txt](https://github.com/mkeet/CLaRO/files/5159258/failure.txt)

**Comment by johncleveland** [comment]
![Screenshot from 2020-09-01 16-39-14](https://user-images.githubusercontent.com/18667146/91916559-4cf87680-ec72-11ea-9831-4ede53deb1ca.png)

**Comment by AdeebNqo** [comment]
Hello @johncleveland,

I was able to reproduce your error on Ubuntu 18.04 LTS + Java 11

The reason why you can't run the jar is the absence of JAXB on Java 11. It was deprecated as of Java 9 and completely removed in Java 11.

As pointed out by @mkeet, the jar should run without any errors using Java 8. If you're using Java 9 and 10, then you should add the module "java.xml.bind" then the jar will work just fine.

Support for Java >=11 will be added soon.

**Comment by johncleveland** [comment]
Thanx for your prompt response.
1. Java 8 does not recognize --module-path and the regular jar  commands throw errors see attch
2. I installed java 10, added java.xml.bind see attch
![Screenshot from 2020-09-02 13-06-54](https://user-images.githubusercontent.com/18667146/92031971-4aebf180-ed1e-11ea-80f8-58eead6b3b45.png)
![Screenshot from 2020-09-02 13-13-30](https://user-images.githubusercontent.com/18667146/92031989-52ab9600-ed1e-11ea-9201-e0dc077ee46b.png)

**Comment by AdeebNqo** [comment]
Hi @johncleveland,

I am unable to reproduce the error you have on Java 8. I am using the same version of Ubuntu as you. Please see the following screenshot:

![Screenshot from 2020-09-03 15-13-18](https://user-images.githubusercontent.com/2272078/92119538-3c720880-edf8-11ea-91c3-59945c8748fc.png)

**Comment by johncleveland** [comment]
If using openjdk must also have openjfx
sudo apt-get install openjfx
Or use oracle jdk8:  https://www.oracle.com/java/technologies/javase-downloads.html

thanx
